---
name: Build master and master

on:
  push:
    branches: dockerfile-contrib-action

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: larstobi
          password: ${{ secrets.LARSTOBI_GITHUB_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.contrib
          push: true
          tags: ghcr.io/larstobi/zwavejs2mqtt:dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
